### ISSUE TITLE
Schema

### ISSUE THREAD

**Issue by thisislawatts** [southlondonmakerspace/membership-system#25]
One of the things we talked about last night was adjusting how the membership permissions are stored. At the moment they exist as:
```js
var memberSchema = mongoose.Schema( {
  ...
  permissions: [ {
    permission: {
      type: ObjectId,
      ref: 'Permissions',
      required: true
    },
    date_added: {
      type: Date,
      default: Date.now,
      required: true
    },
    date_updated: {
      type: Date,
      default: Date.now,
      required: true
    },
    date_expires: {
      type: Date
    }
  } ]
} );
```

Put perhaps we need to reference another document. This would allow us to independently update the type of 

```js
var memberSchema = mongoose.Schema( {
  ...
  permissions: [ {
    type: ObjectId,
    ref: 'Access',
    required: true
  } ]
} );

var accessSchema = mongoose.Schema( {
  permission: {
    type: ObjectId,
    ref: 'Permissions',
    required: true
  },
  member: {
    type: ObjectId,
    ref: 'Members',
    required: true
  },
  date_added: {
    type: Date,
    default: Date.now,
    required: true
  },
  date_updated: {
    type: Date,
    default: Date.now,
    required: true
  },
  date_expires: {
    type: Date
  }
});

```

It was reading through this series [1](http://blog.mongodb.org/post/87200945828/6-rules-of-thumb-for-mongodb-schema-design-part-1), [2](http://blog.mongodb.org/post/87892923503/6-rules-of-thumb-for-mongodb-schema-design-part-2), [3](http://blog.mongodb.org/post/88473035333/6-rules-of-thumb-for-mongodb-schema-design-part-3), that got me thinking this might be a good way to go.

Having individual Access objects in this manner:

* Allow us to quickly pull up everyone with `DoorRights`
* Easy administration of individual access, ie. Luke's misplaced his keys, revoke all `DoorRights`

Aware that there will need to be some refactoring if we affect a schema change but I think it's worth taking the time on this foundation. Let me know your thoughts!

**Comment by squaredoffagain** [comment]
I'm perhaps missing the point here, but the guidelines linked in 3 includes the following:
> **One:** favo[u]r embedding unless there is a compelling reason not to

Unless something has radically changed since my last visit, all _n_ are small. There are a small number of members, a small number of permissions, each member has some small number of permissions. Mostly one-to-few relationships.

The only natural one-to-many relation I can see (which _would_ justify the schema change according to the guidelines) is if we want a full audit of all accesses over the whole of history; or if we have problems with storage or performance running on the available h/w.

Could you state what the compelling reason for the change to an array of references would be?
Is mongo truly incapable of getting everyone with `DoorRights` without this change?

**Comment by unknowndomain** [comment]
Mondo goes my support doing an update wrote to a single key in an object in an array. You have to write the whole array which will lead to non atomic writing or something.

**Comment by thisislawatts** [comment]
With some space and time I would vote for keeping the existing embedded model. @squaredoffagain is right that given the current scale there's little need for complicating the schema more than necessary.

**Comment by unknowndomain** [comment]
Resolved, not sure if the updates are atomic or not, lets hope for the best
